-- AlterTable
ALTER TABLE `rolepermission` MODIFY `permission` ENUM('VIEW_DASHBOARD', 'MANAGE_PROFILE', 'MANAGE_USERS', 'MANAGE_ROLES', 'MANAGE_PERMISSIONS', 'MANAGE_STUDENTS', 'MANAGE_GRADES', 'MANAGE_SCHEDULES', 'VIEW_GRADES', 'VIEW_SCHEDULES', 'VIEW_CHILD_GRADES', 'VIEW_CHILD_SCHEDULES', 'SUPER_TEACHER') NOT NULL;
